users:
  maximum_username: 50
  minimum_username: 5
  maximum_password: 50
  minimum_password: 6
remember:
  ischeck: "1"
size:
  gravatar: 80
  image: 85
  user_image: 18
  minimum_image: 5
image_default: "avatar02.png"
warning:
  avatar: "should be less than 5MB"
  limit: [400, 400]
per_page: 3
image:
  maximum_length: 50
trainer:
  per_page: 4
